/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author modab5310
 */
public class Purchasing extends javax.swing.JFrame {

    /**
     * Creates new form Purchasing
     */
    public Purchasing() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        Titlee = new javax.swing.JLabel();
        First = new javax.swing.JLabel();
        FirstAddition = new javax.swing.JLabel();
        FirstAddition2 = new javax.swing.JLabel();
        FirstAddition3 = new javax.swing.JLabel();
        Second = new javax.swing.JLabel();
        SecondAddition = new javax.swing.JLabel();
        SecondAddition2 = new javax.swing.JLabel();
        Third = new javax.swing.JLabel();
        ThirdAddition = new javax.swing.JLabel();
        ThirdAddition2 = new javax.swing.JLabel();
        Calculate = new javax.swing.JButton();
        FirstTextfield = new javax.swing.JTextField();
        FirstTextfield2 = new javax.swing.JTextField();
        FirstTextfield3 = new javax.swing.JTextField();
        FirstTextfield4 = new javax.swing.JTextField();
        SecondTextfield = new javax.swing.JTextField();
        SecondTextfield2 = new javax.swing.JTextField();
        SecondTextfield3 = new javax.swing.JTextField();
        ThirdTextfield = new javax.swing.JTextField();
        ThirdTextfield2 = new javax.swing.JTextField();
        ThirdTextfield3 = new javax.swing.JTextField();
        Taxes = new javax.swing.JLabel();
        Subtotal = new javax.swing.JLabel();
        Grandtotal = new javax.swing.JLabel();
        TaxTotal = new javax.swing.JLabel();
        Subbtotal = new javax.swing.JLabel();
        Final = new javax.swing.JLabel();

        jLabel2.setText("jLabel2");

        jLabel4.setText("jLabel4");

        jLabel6.setText("jLabel6");

        jLabel1.setText("jLabel1");

        jTextField4.setText("jTextField4");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(153, 255, 255));

        Titlee.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        Titlee.setText("BreaktheFast ");

        First.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        First.setText("Roasted Bagels ($2.99) ");

        FirstAddition.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        FirstAddition.setText("Cream Cheese ($1.99)");

        FirstAddition2.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        FirstAddition2.setText("Strawberry Jam($1.99)");

        FirstAddition3.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        FirstAddition3.setText("Butter($1.99)");

        Second.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        Second.setText("Strawberry Smoothie($3.99)");

        SecondAddition.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        SecondAddition.setText("Cherry Flavour($3.99) ");

        SecondAddition2.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        SecondAddition2.setText("Banana Flavour($3.99)");

        Third.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        Third.setText("Chocolate Icecream($4.99)");

        ThirdAddition.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        ThirdAddition.setText("Vanilla Icecream($4.99)");

        ThirdAddition2.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        ThirdAddition2.setText("Vanilla & Chocolate Icecream($4.99)");

        Calculate.setText("Calculate");
        Calculate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CalculateActionPerformed(evt);
            }
        });

        Taxes.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        Taxes.setText("TAXES ( 13%) : ");

        Subtotal.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        Subtotal.setText("Subtotal: ");

        Grandtotal.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        Grandtotal.setText("Grandtotal: ");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(First)
                                    .addComponent(FirstAddition))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(FirstTextfield2, javax.swing.GroupLayout.DEFAULT_SIZE, 49, Short.MAX_VALUE)
                                    .addComponent(FirstTextfield)))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addComponent(FirstAddition2)
                                .addGap(33, 33, 33)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(FirstTextfield4, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(FirstTextfield3))))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(63, 63, 63)
                                .addComponent(Calculate))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(35, 35, 35)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(Subtotal)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(Subbtotal, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(Grandtotal)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(Final, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(Taxes)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(TaxTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGap(24, 24, 24))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(SecondAddition)
                                    .addComponent(SecondAddition2, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(FirstAddition3)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Third)
                                    .addComponent(ThirdAddition))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(ThirdTextfield2, javax.swing.GroupLayout.DEFAULT_SIZE, 46, Short.MAX_VALUE)
                                    .addComponent(ThirdTextfield)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(ThirdAddition2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ThirdTextfield3, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(133, 133, 133)
                        .addComponent(Titlee))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(Second)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(SecondTextfield2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(SecondTextfield, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(SecondTextfield3, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Titlee)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(First)
                    .addComponent(Calculate)
                    .addComponent(FirstTextfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(FirstAddition)
                    .addComponent(FirstTextfield2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(FirstAddition2)
                    .addComponent(FirstTextfield3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Taxes)
                    .addComponent(TaxTotal))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(FirstAddition3)
                    .addComponent(FirstTextfield4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(2, 2, 2)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Subtotal)
                    .addComponent(Subbtotal))
                .addGap(2, 2, 2)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Second)
                    .addComponent(SecondTextfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SecondAddition)
                    .addComponent(SecondTextfield2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Grandtotal)
                    .addComponent(Final))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SecondAddition2)
                    .addComponent(SecondTextfield3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Third)
                    .addComponent(ThirdTextfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ThirdAddition)
                    .addComponent(ThirdTextfield2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ThirdAddition2)
                    .addComponent(ThirdTextfield3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CalculateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CalculateActionPerformed

        // constants
        final double BAGEL = 2.99;
        final double CREAM_BAGEL = 1.99;
        final double JAM = 1.99; 
        final double BUTTER = 1.99; 
        final double STRAW_SMOOTH = 3.99;
        final double CHERRY_SMOOTH = 3.99; 
        final double BANANA_SMOOTH = 3.99;
        final double CHOC_ICE = 4.99; 
        final double VAN_ICE = 4.99; 
        final double MIX_ICE = 4.99; 
        final double TAX_RATE = 0.13;        
        
        // variables 
        int num1; 
        int num2; 
        int num3;
        int num4;
        int num5; 
        int num6;
        int num7;
        int num8; 
        int num9; 
        int num10; 
        double taxtotal;
        double subtotal;
        double grandtotal; 
        
        
        // parsing 
        
        num1 = Integer.parseInt(FirstTextfield.getText()); 
        num2 = Integer.parseInt(FirstTextfield2.getText()); 
        num3 = Integer.parseInt(FirstTextfield3.getText()); 
        num4 = Integer.parseInt(FirstTextfield4.getText()); 
        num5 = Integer.parseInt(SecondTextfield.getText()); 
        num6 = Integer.parseInt(SecondTextfield2.getText());
        num7 = Integer.parseInt(SecondTextfield3.getText()); 
        num8 = Integer.parseInt(ThirdTextfield.getText()); 
        num9 = Integer.parseInt(ThirdTextfield2.getText()); 
        num10 = Integer.parseInt(ThirdTextfield3.getText()); 
        
        
        // algorithm 
        
        subtotal = ( num1 * BAGEL ) + ( num2 * CREAM_BAGEL ) + ( num3 * JAM ) + ( num4 * BUTTER ) + ( num5 * STRAW_SMOOTH) + ( num6 * CHERRY_SMOOTH )+(num7 * BANANA_SMOOTH) + ( num8*CHOC_ICE) + ( num9* VAN_ICE ) + (num10 + MIX_ICE);
        
        taxtotal = subtotal * 0.13; 
        grandtotal = subtotal + taxtotal; 
        
        
        
        // output 
        
        TaxTotal.setText(String.valueOf(taxtotal)); 
        Subbtotal.setText(String.valueOf(subtotal)); 
        Final.setText(String.valueOf(grandtotal)); 
 
    }//GEN-LAST:event_CalculateActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Purchasing.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Purchasing.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Purchasing.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Purchasing.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Purchasing().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Calculate;
    private javax.swing.JLabel Final;
    private javax.swing.JLabel First;
    private javax.swing.JLabel FirstAddition;
    private javax.swing.JLabel FirstAddition2;
    private javax.swing.JLabel FirstAddition3;
    private javax.swing.JTextField FirstTextfield;
    private javax.swing.JTextField FirstTextfield2;
    private javax.swing.JTextField FirstTextfield3;
    private javax.swing.JTextField FirstTextfield4;
    private javax.swing.JLabel Grandtotal;
    private javax.swing.JLabel Second;
    private javax.swing.JLabel SecondAddition;
    private javax.swing.JLabel SecondAddition2;
    private javax.swing.JTextField SecondTextfield;
    private javax.swing.JTextField SecondTextfield2;
    private javax.swing.JTextField SecondTextfield3;
    private javax.swing.JLabel Subbtotal;
    private javax.swing.JLabel Subtotal;
    private javax.swing.JLabel TaxTotal;
    private javax.swing.JLabel Taxes;
    private javax.swing.JLabel Third;
    private javax.swing.JLabel ThirdAddition;
    private javax.swing.JLabel ThirdAddition2;
    private javax.swing.JTextField ThirdTextfield;
    private javax.swing.JTextField ThirdTextfield2;
    private javax.swing.JTextField ThirdTextfield3;
    private javax.swing.JLabel Titlee;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField4;
    // End of variables declaration//GEN-END:variables
}
